language: python
python:
        - "3.6"
cache: pip
install:
        - pip install pylint
script:
        - pylint start.py
        - pylint rise/startwindow.py
        - pylint process/grraphic.py
        - pylint end/endwindow.py
        - python -m unittest discover
