language: python
python:
        - "3.6"
cache: pip
install:
        - pip install flake8
script:
        - flake8 main.py
        - flake8 graphic.py
        - flake8 verbs.py
        - flake8 test.py
        - python -m unittest discover
