language: python
python:
        - "3.6"
cache: pip
install:
        - pip install pylint
script:
        - pylint start.py --disable=all --enable=similarities,W,E
        - pylint rise/startwindow.py --disable=all --enable=similarities,W,E
        - pylint process/graphic.py --disable=all --enable=similarities,W,E
        - pylint end/endwindow.py --disable=all --enable=similarities,W,E
        - python -m unittest discover
